version: '3'
services:

  app:
    container_name: fbd_app
    build:
      context: .
    image: fbd_app:dev
    tty: true
    environment:
      - DB_HOST=db
      - DB_NAME=fbd_app
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_ADAPTER=postgres
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
      - bundle-volume:/usr/src/bundle
    command: 'bundle exec rackup --host 0.0.0.0 -p 3000'

  db:
    container_name: db
    build:
      context: .
      dockerfile: postgres/Dockerfile.postgres
    image: fbd_app_db:dev
    volumes:
      - ./.volumes/postgres/:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      - POSTGRES_DB_NAME=fbd_app
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

volumes:
  bundle-volume:
